# Generated by Django 5.1.6 on 2025-02-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriasproduto',
            fields=[
                ('idcategoriaproduto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoriasproduto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('nick', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('datacriacao', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consoles',
            fields=[
                ('idconsole', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('precomeia', models.FloatField()),
                ('precohora', models.FloatField()),
                ('status', models.IntegerField(db_comment='1- DISPONIVEL 2- DEFEITO 3- MANUTENÇÃO')),
                ('precocompra', models.FloatField()),
            ],
            options={
                'db_table': 'consoles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pausas',
            fields=[
                ('idpausa', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pausas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('idproduto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('qtdestoque', models.IntegerField()),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('idsessao', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('tempominuto', models.BigIntegerField()),
                ('status', models.IntegerField(db_comment='0- FINALIZADO 1- ATIVO 2- PAUSADO')),
            ],
            options={
                'db_table': 'sessao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tvs',
            fields=[
                ('idtv', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('status', models.IntegerField(db_comment='1- DISPONIVEL 2- DEFEITO -3 MANUTENÇÃO')),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('polegadas', models.CharField(blank=True, max_length=100, null=True)),
                ('precocompra', models.FloatField()),
            ],
            options={
                'db_table': 'tvs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('idvenda', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('valortotal', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendas',
                'managed': False,
            },
        ),
    ]
