# Generated by Django 5.1.6 on 2025-02-14 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_tempo_minuto_sessao_tempo_segundo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Desabilitado')], default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='sessao',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ativo'), (0, 'Desabilitado')], default=1),
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancelada'), (1, 'Aprovada')], default=1),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.formapagamento'),
        ),
        migrations.CreateModel(
            name='VendaItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.venda')),
            ],
        ),
    ]
